title: Fandr's Life
author: Fandrn
email: fangyoy1995+farn.app@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
      JUST for daily life.
# social links
twitter_username: fangdrn
github_username:  fandrn
github_username:  Veroer

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
